#!/bin/sh

clock=$(date '+%I')

icon=" "

case $BLOCK_BUTTON in
	1) notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -D ~/.config/calcurse -d3)" ;;
	2) setsid "$TERMINAL" -e calcurse -D ~/.config/calcurse & ;;
	3) notify-send "📅 Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac


#for europeans, use this
printf '    %s %s%s   \n' "$(date '+ %d/%m/%Y')" "$icon" "$(date '+%H:%M%p')"
