#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "RAM Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	2) setsid "$TERMINAL" -e htop & ;;
	3) notify-send "RAM Memory module" "\- Shows Memory Used/Total.
- Click to show memory hogs.
- Middle click to open htop." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

free -h | sed -n '2{p;q}' | awk '{print $3 "/" $2}'
